credentials:
  usernames:
    guestuser:
      email: ntacyodelphin@gmail.com
      name: Test User
      password: passcode
cookie:
  expiry_days: 30
  key: cookie_signature_key
  name: cookie_name
pre-authorized:
  usernames:
    - TestUser
